### ISSUE TITLE
Multiplayer & Sharing domains

### ISSUE THREAD

**Issue by reesericci** [obl-ong/admin#29]
Obl.ong should have a way to share a domain between multiple users, and have multiplayer features like Figma or google docs. You should be able to see the other's cursor, have simple cursor chat, and watch them create records and update settings live. This will make working on domains together super easy, and remote troubleshooting a breeze.

**Comment by youngchief-btw** [comment]
I don't know how well of a UX having multiplayer would have. Sure, definitely sharing domains. But not quite sold on multiplayer yet. Just seems like added complexity and I don't see it being used much. Usually you set up a domain once, and rarely end up touching the records unless your doing DDNS or something. And even then, you don't need multiplayer since it's just scripting and there is usually no need for touching things manually at the same time with others.

**Comment by reesericci** [comment]
I looked into this, and there's no simple(ish) way to accomplish this - it would be a lot of custom engineering. A better path would just to be morphing updates, going to break this out into two seperate issues.

I think multiplayer would still be an excellent feature, and would love to reconsider down the line - but for now I'm closing as wontfix.
